security:
    password_hashers:
        App\Entity\User: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # /api/users/my endpoint'iga POST orqali murojaat qilinganda - token so'ralmasin
        user_create:
            pattern: ^/api/users/my$
            methods:
                - post
            security: false

        news_create:
            pattern: ^/api/getAllNews$
            methods:
                - get
            security: false

        all_news:
            pattern: ^/api/new_pages/
            methods:
                - get
            security: false

        news_get:
            pattern: ^/api/getNewsThree$
            methods:
                - get
            security: false

        leader_get:
            pattern: ^/api/leaderships$
            methods:
                - get
            security: false    

        tariff_get:
            pattern: ^/api/tariffs$
            methods:
                - get
            security: false 

 

        main:
            stateless: true
            provider: app_user_provider
            json_login:
                check_path: /api/users/auth
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~

    access_control:
        - { path: ^/api/.+, roles: PUBLIC_ACCESS}
        - { path: ^/api, roles: PUBLIC_ACCESS}

